name: Workflow

on:
  workflow_dispatch:

jobs:
  Job_1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.ORG_SECRET }}
        run: |
          echo "$SUPER_SECRET"
